spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.154/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx165c95075b074969
  mpAppSecret: d694af83c4221f0bcd5dc80e9ab9f4d4
  mchId: 1522502101
  mchKey: lxy19940410timelxy19940410timelx
  keyPath: /Users/xinyuan/Downloads/cert/apiclient_cert.p12
  notifyUrl: http://tkft.nat100.top/sell/pay/notify